import { afterEach,describe,expect,it,vi } from "vitest";
import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import KevPortal from "./KevPortal";

afterEach(()=>{cleanup();vi.restoreAllMocks();history.replaceState({},"","/");});

const record={cveID:"CVE-2026-0001",vendorProject:"Acme",product:"Edge",vulnerabilityName:"Remote issue",dateAdded:"2026-09-01",dueDate:"2026-09-22",knownRansomwareCampaignUse:"Known",requiredAction:"Patch",notes:"",cwes:["CWE-79"],remediationDays:21};
const dataset={title:"CISA KEV",catalogVersion:"2026.09.16",dateReleased:"2026-09-16T00:00:00Z",retrievedAt:"2026-09-16T01:00:00Z",sourceUrl:"https://www.cisa.gov/known-exploited-vulnerabilities-catalog",records:Array.from({length:30},(_,index)=>index===0?record:{...record,cveID:`CVE-2026-${String(index+1).padStart(4,"0")}`,vendorProject:index%2?"Bravo":"Acme",product:index%2?"Server":"Edge",vulnerabilityName:`Issue ${index+1}`,knownRansomwareCampaignUse:"Unknown",notes:index===1?undefined:"",cwes:index===1?undefined:["CWE-79"]})};
const response=(body:unknown,ok=true)=>Promise.resolve({ok,json:()=>Promise.resolve(body)} as Response);

describe("KevPortal shell",()=>{
  it("shows loading and then the validated snapshot",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);expect(screen.getByText(/Loading the CISA snapshot/i)).toBeTruthy();expect(await screen.findByRole("heading",{name:/Security intelligence, prioritized/i})).toBeTruthy();});
  it("distinguishes an invalid snapshot",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response({...dataset,records:undefined})));render(<KevPortal/>);expect(await screen.findByText(/Snapshot format not recognized/i)).toBeTruthy();});
  it("falls back when browser storage is blocked",async()=>{vi.spyOn(window,"localStorage","get").mockImplementation(()=>{throw new Error("blocked")});vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);expect(await screen.findByRole("heading",{name:/Security intelligence, prioritized/i})).toBeTruthy();});
  it("retries a failed fetch",async()=>{const fetchMock=vi.fn().mockRejectedValueOnce(new Error("offline")).mockImplementationOnce(()=>response(dataset));vi.stubGlobal("fetch",fetchMock);render(<KevPortal/>);fireEvent.click(await screen.findByRole("button",{name:/retry/i}));expect(await screen.findByRole("heading",{name:/Security intelligence, prioritized/i})).toBeTruthy();expect(fetchMock).toHaveBeenCalledTimes(2);});
  it("navigates to the Explorer and updates the URL",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);fireEvent.click(await screen.findByRole("button",{name:/vulnerability explorer/i}));expect(screen.getByRole("heading",{name:"Vulnerability Explorer"})).toBeTruthy();expect(location.search).toContain("view=explorer");});
  it("resets coordinated filters",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);const vendor=await screen.findByLabelText("Vendor") as HTMLSelectElement;fireEvent.change(vendor,{target:{value:"Acme"}});expect(vendor.value).toBe("Acme");fireEvent.click(screen.getByRole("button",{name:/reset filters/i}));expect(vendor.value).toBe("");});
  it("keeps source metadata and accessible chart summaries visible",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);await waitFor(()=>expect(screen.getByText(/Catalog 2026.09.16/i)).toBeTruthy());expect(screen.getByRole("link",{name:/official CISA source/i}).getAttribute("href")).toBe(dataset.sourceUrl);expect(screen.getByText(/Priority distribution summary:/i)).toBeTruthy();expect(screen.getByText(/Vendor concentration summary:/i)).toBeTruthy();expect(screen.getByText(/Catalog additions summary:/i)).toBeTruthy();expect(screen.getByText(/Ransomware-linked products summary:/i)).toBeTruthy();});
});

describe("explorer, drawer, watchlist, and notes",()=>{
  it("searches, empties combined filters, and resets results",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);fireEvent.click(await screen.findByRole("button",{name:/vulnerability explorer/i}));const search=screen.getByRole("searchbox",{name:/search vulnerabilities/i});fireEvent.change(search,{target:{value:"CVE 2026 0002"}});expect(await screen.findByRole("button",{name:/Open CVE-2026-0002/i})).toBeTruthy();fireEvent.change(screen.getByLabelText("Explorer vendor"),{target:{value:"Acme"}});expect(screen.getByText(/No vulnerabilities match/i)).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:/clear explorer filters/i}));expect(screen.getByRole("button",{name:/Open CVE-2026-0001/i})).toBeTruthy();});
  it("sorts results and expands the page size",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);fireEvent.click(await screen.findByRole("button",{name:/vulnerability explorer/i}));expect(screen.getAllByRole("button",{name:/Open CVE-/i})).toHaveLength(25);fireEvent.change(screen.getByLabelText("Rows per page"),{target:{value:"50"}});expect(screen.getAllByRole("button",{name:/Open CVE-/i})).toHaveLength(30);fireEvent.change(screen.getByLabelText("Sort results"),{target:{value:"newest"}});expect(screen.getAllByRole("button",{name:/Open CVE-/i})[0].textContent).toContain("CVE-");});
  it("opens details, persists watchlist and notes, and shows missing-source fallbacks",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);fireEvent.click(await screen.findByRole("button",{name:/vulnerability explorer/i}));const opener=screen.getByRole("button",{name:/Open CVE-2026-0002/i});opener.focus();fireEvent.click(opener);expect(await screen.findByRole("dialog")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:/add to watchlist/i}));expect(screen.getByRole("button",{name:/remove from watchlist/i})).toBeTruthy();const note=screen.getByLabelText("Analyst note") as HTMLTextAreaElement;note.focus();fireEvent.change(note,{target:{value:"Investigate exposed server"}});expect(note.value).toBe("Investigate exposed server");expect(document.activeElement).toBe(note);expect(screen.getAllByText("Not provided by CISA").length).toBeGreaterThan(0);fireEvent.click(screen.getByRole("button",{name:/close details/i}));await waitFor(()=>expect(document.activeElement).toBe(opener));fireEvent.click(opener);expect((await screen.findByLabelText("Analyst note") as HTMLTextAreaElement).value).toBe("Investigate exposed server");});
});

describe("vendor intelligence and briefing",()=>{
  it("profiles a selectable vendor and exposes comparison signals",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);fireEvent.click(await screen.findByRole("button",{name:/vendor intelligence/i}));const vendor=screen.getByLabelText("Vendor profile") as HTMLSelectElement;expect([...vendor.options].map((option)=>option.value)).toEqual(["Acme","Bravo"]);fireEvent.change(vendor,{target:{value:"Bravo"}});expect(screen.getByRole("heading",{name:/Bravo profile/i})).toBeTruthy();expect(screen.getByText(/Product breakdown summary:/i)).toBeTruthy();expect(screen.getAllByText(/catalog entries/i).length).toBeGreaterThan(0);expect(screen.getByText(/ransomware-linked/i)).toBeTruthy();});
  it("builds a scoped methodology briefing with three priority records",async()=>{vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);fireEvent.click(await screen.findByRole("button",{name:/briefing & methodology/i}));expect(screen.getByRole("heading",{name:/Decision briefing/i})).toBeTruthy();expect(screen.getByRole("heading",{name:/KEV Action Priority methodology/i})).toBeTruthy();expect(screen.getByText(/30 catalog entries in the active scope/i)).toBeTruthy();expect(screen.getAllByTestId("briefing-priority-record")).toHaveLength(3);});
  it("prints the briefing",async()=>{const print=vi.fn();vi.stubGlobal("print",print);vi.stubGlobal("fetch",vi.fn(()=>response(dataset)));render(<KevPortal/>);fireEvent.click(await screen.findByRole("button",{name:/briefing & methodology/i}));fireEvent.click(screen.getByRole("button",{name:/print briefing/i}));expect(print).toHaveBeenCalledOnce();});
});
