"use client";
import { useEffect,useMemo,useState } from "react";
import { Bar,BarChart,CartesianGrid,Cell,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { AlertTriangle,CalendarClock,Database,RotateCcw,ShieldAlert,ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { NativeSelect,NativeSelectOption } from "@/components/ui/native-select";
import { deriveMetrics,groupCount } from "@/src/kev/metrics";
import type { DashboardFilters,KevDataset,KevRecord } from "@/src/kev/types";

const EMPTY:DashboardFilters={vendor:"",year:"",ransomware:""};
const EMPTY_RECORDS:KevRecord[]=[];
const tip={background:"#111c2e",border:"1px solid #2b3b55",borderRadius:10,color:"#e8f1ff"};
function MetricCard({label,value,detail,icon:Icon,tone="cyan"}:{label:string;value:string;detail:string;icon:typeof Database;tone?:"cyan"|"amber"|"red"}){return <article className={`metric-card metric-${tone}`}><div className="metric-icon"><Icon aria-hidden="true" size={18}/></div><p>{label}</p><strong>{value}</strong><span>{detail}</span></article>}
function ChartCard({eyebrow,title,takeaway,children}:{eyebrow:string;title:string;takeaway:string;children:React.ReactNode}){return <section className="chart-card"><div className="chart-heading"><div><span>{eyebrow}</span><h2>{title}</h2></div><p>{takeaway}</p></div><div className="chart-wrap" role="img" aria-label={`${title}. ${takeaway}`}>{children}</div></section>}

export default function KevDashboard(){
 const [dataset,setDataset]=useState<KevDataset|null>(null),[error,setError]=useState(""),[filters,setFilters]=useState<DashboardFilters>(EMPTY);
 useEffect(()=>{fetch("/data/kev-clean.json").then(r=>{if(!r.ok)throw new Error("Unable to load the public CISA snapshot.");return r.json()}).then(setDataset).catch(e=>setError(e.message))},[]);
 const records=dataset?.records??EMPTY_RECORDS,metrics=useMemo(()=>deriveMetrics(records,filters),[records,filters]);
 const vendors=useMemo(()=>[...new Set(records.map(r=>r.vendorProject))].sort(),[records]),years=useMemo(()=>[...new Set(records.map(r=>r.dateAdded.slice(0,4)))].sort().reverse(),[records]);
 const vendorData=useMemo(()=>groupCount(metrics.filtered,r=>r.vendorProject).slice(0,10),[metrics.filtered]);
 const trendData=useMemo(()=>groupCount(metrics.filtered,r=>r.dateAdded.slice(0,7)).sort((a,b)=>a.name.localeCompare(b.name)).slice(-36),[metrics.filtered]);
 const ransomwareData=useMemo(()=>groupCount(metrics.filtered.filter(r=>r.knownRansomwareCampaignUse==="Known"),r=>r.product).slice(0,8),[metrics.filtered]);
 const remediationData=useMemo(()=>[{name:"0–7",min:0,max:7},{name:"8–14",min:8,max:14},{name:"15–21",min:15,max:21},{name:"22–30",min:22,max:30},{name:"31+",min:31,max:Infinity}].map(b=>({name:b.name,count:metrics.filtered.filter(r=>r.remediationDays>=b.min&&r.remediationDays<=b.max).length})),[metrics.filtered]);
 if(error)return <main className="status-screen"><AlertTriangle/><h1>Dataset unavailable</h1><p>{error}</p></main>;
 if(!dataset)return <main className="status-screen"><div className="pulse-shield"><ShieldCheck/></div><h1>Loading the CISA snapshot…</h1></main>;
 const update=(key:keyof DashboardFilters,value:string)=>setFilters(c=>({...c,[key]:value})),top=vendorData[0],release=new Date(dataset.dateReleased).toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric"}),pct=(metrics.ransomwareShare*100).toFixed(1),microsoftCount=records.filter(record=>record.vendorProject==="Microsoft").length,knownRansomwareCount=records.filter(record=>record.knownRansomwareCampaignUse==="Known").length;
 return <main className="dashboard-shell">
  <header className="hero"><div className="brand-lockup"><span><ShieldAlert size={18}/></span> CISA KEV • RISK CONCENTRATION</div><p className="kicker">KNOWN EXPLOITED VULNERABILITIES / CATALOG {dataset.catalogVersion}</p><h1>Where exploitation risk <em>concentrates.</em></h1><p className="hero-copy">Microsoft accounts for {((microsoftCount/records.length)*100).toFixed(1)}% of catalog entries, while confirmed ransomware use appears in {((knownRansomwareCount/records.length)*100).toFixed(1)}%—a reminder to prioritize by evidence, exposure, and business impact.</p><div className="source-line"><span className="live-dot"/> Snapshot released {release} <span>•</span> {records.length.toLocaleString()} public records <span>•</span> <a href="https://www.cisa.gov/known-exploited-vulnerabilities-catalog" target="_blank" rel="noreferrer">Official CISA source ↗</a></div></header>
  <section className="metrics-grid" aria-label="Filtered summary metrics"><MetricCard label="KEV entries" value={metrics.total.toLocaleString()} detail="Known exploitation evidence" icon={Database}/><MetricCard label="Vendors represented" value={metrics.vendors.toLocaleString()} detail="CISA-provided labels" icon={ShieldCheck}/><MetricCard label="Ransomware confirmed" value={metrics.knownRansomware.toLocaleString()} detail={`${pct}% of this view`} icon={ShieldAlert} tone="red"/><MetricCard label="Median remediation window" value={`${metrics.medianRemediationDays} days`} detail="Federal due-date window" icon={CalendarClock} tone="amber"/></section>
  <section className="filter-panel" aria-label="Dashboard filters"><div><p>FILTER THE EVIDENCE</p><span>Every metric and chart updates together.</span></div><label>Vendor<NativeSelect value={filters.vendor} onChange={e=>update("vendor",e.target.value)}><NativeSelectOption value="">All vendors</NativeSelectOption>{vendors.map(v=><NativeSelectOption key={v} value={v}>{v}</NativeSelectOption>)}</NativeSelect></label><label>Year added<NativeSelect value={filters.year} onChange={e=>update("year",e.target.value)}><NativeSelectOption value="">All years</NativeSelectOption>{years.map(y=><NativeSelectOption key={y} value={y}>{y}</NativeSelectOption>)}</NativeSelect></label><label>Ransomware status<NativeSelect value={filters.ransomware} onChange={e=>update("ransomware",e.target.value)}><NativeSelectOption value="">Known + Unknown</NativeSelectOption><NativeSelectOption value="Known">Known</NativeSelectOption><NativeSelectOption value="Unknown">Unknown</NativeSelectOption></NativeSelect></label><Button variant="outline" onClick={()=>setFilters(EMPTY)}><RotateCcw size={16}/> Reset</Button></section>
  {!metrics.total?<section className="empty-state"><h2>No records match this view.</h2><p>Try widening one of the filters or reset the dashboard.</p><Button onClick={()=>setFilters(EMPTY)}>Reset filters</Button></section>:<section className="charts-grid">
   <ChartCard eyebrow="COMPARE" title="Vulnerability concentration by vendor" takeaway={top?`${top.name} leads this view with ${top.count} entries.`:"No vendor entries in this view."}><ResponsiveContainer width="100%" height={330}><BarChart data={vendorData} layout="vertical" margin={{left:12,right:24}}><CartesianGrid stroke="#22314a" horizontal={false}/><XAxis type="number" stroke="#8798b4"/><YAxis type="category" dataKey="name" width={88} tick={{fill:"#aebed5",fontSize:12}}/><Tooltip contentStyle={tip} cursor={{fill:"#14233a"}}/><Bar dataKey="count" name="KEV entries" radius={[0,6,6,0]} onClick={entry=>update("vendor",String(entry.name))}>{vendorData.map((e,i)=><Cell key={e.name} fill={i===0?"#36d5e8":"#287b9f"} className="clickable-bar"/>)}</Bar></BarChart></ResponsiveContainer></ChartCard>
   <ChartCard eyebrow="BREAK DOWN" title="Catalog additions over the last 36 months" takeaway="Date added tracks catalog admission—not disclosure or first exploitation."><ResponsiveContainer width="100%" height={330}><LineChart data={trendData} margin={{left:0,right:16}}><CartesianGrid stroke="#22314a" vertical={false}/><XAxis dataKey="name" stroke="#8798b4" tick={{fontSize:11}} minTickGap={36}/><YAxis stroke="#8798b4" width={34}/><Tooltip contentStyle={tip}/><Line type="monotone" dataKey="count" name="Entries added" stroke="#36d5e8" strokeWidth={3} dot={false} activeDot={{r:5,fill:"#ffb454"}}/></LineChart></ResponsiveContainer></ChartCard>
   <ChartCard eyebrow="FIND EXCEPTIONS" title="Products with confirmed ransomware use" takeaway="‘Unknown’ means unconfirmed—not evidence of no ransomware use."><ResponsiveContainer width="100%" height={320}><BarChart data={ransomwareData} margin={{left:0,right:16}}><CartesianGrid stroke="#22314a" vertical={false}/><XAxis dataKey="name" stroke="#8798b4" tick={{fill:"#aebed5",fontSize:11}} interval={0} angle={-18} textAnchor="end" height={65}/><YAxis stroke="#8798b4" width={34}/><Tooltip contentStyle={tip}/><Bar dataKey="count" name="Known ransomware" fill="#ff6474" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartCard>
   <ChartCard eyebrow="RE-MEASURE" title="Federal remediation windows" takeaway={`${metrics.medianRemediationDays} days is the median assigned window in this view.`}><ResponsiveContainer width="100%" height={320}><BarChart data={remediationData} margin={{left:0,right:16}}><CartesianGrid stroke="#22314a" vertical={false}/><XAxis dataKey="name" stroke="#8798b4"/><YAxis stroke="#8798b4" width={42}/><Tooltip contentStyle={tip}/><Bar dataKey="count" name="KEV entries" radius={[6,6,0,0]}>{remediationData.map((e,i)=><Cell key={e.name} fill={i<2?"#ffb454":"#36d5e8"}/>)}</Bar></BarChart></ResponsiveContainer></ChartCard>
  </section>}
  <section className="methodology"><div><span>READ THIS CORRECTLY</span><h2>Catalog presence is a prioritization signal—not a vendor scorecard.</h2></div><p>This analysis uses {records.length.toLocaleString()} entries in CISA KEV catalog {dataset.catalogVersion}. No exact duplicate rows or duplicate CVE IDs were present. Due dates are federal remediation deadlines, not universal SLAs. Vendor frequency does not prove insecurity or exposure in any organization. “Unknown” ransomware status remains distinct from “Known.”</p></section>
  <footer><p>Analysis by Adedayo A. Onasanya</p><p>Computing &amp; Security Technology • Drexel University</p><a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noreferrer">CISA KEV data • CC0 1.0</a></footer>
 </main>
}
